/**
 * An exhaustive list of predefined theme names.
 * This constant is used to define available themes for UI components,
 * allowing for a consistent theming system across the application.
 * Marked as `const` to ensure the values are treated as a fixed set of strings,
 * enabling type safety when referencing theme names.
 */
export const themesConst = [
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
] as const
